#!/usr/bin/bash

        echo "Choose an interval for your alarm:";
        read interval;
        clear && echo $interval"minutes";

  progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
    remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
    percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
  done
  clean_line
  }

  progress-bar $interval*60;

        dunstify -t 5000 -h string:fgcolor:#000000 -h string:bgcolor:#FF0013 "TIME TO QUIT";
        mplayer Music/Varie/RcOST.flac
