#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_INFO=${BATTERY_INFO:11}
TIME_LEFT=$(acpi | awk '{print "- " $5}')
ICON=""
COLOR=""

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
if [[ "${BATTERY_POWER}" -le 94 ]]; then
ICON=""
COLOR="#FFFFFF"
else
ICON=""
COLOR="#00FF00"
fi
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
if [[ "${BATTERY_POWER}" -le 10 ]]; then
# BATTERY < 10
ICON=""
COLOR="#FF2222"
elif [[ "${BATTERY_POWER}" -le 25 ]]; then
# 10 < BATTERY < 25
ICON=""
COLOR="#AA9922"
elif [[ "${BATTERY_POWER}" -le 50 ]]; then
# 25 < BATTERY < 50
ICON=""
COLOR="#99FF33"
elif [[ "${BATTERY_POWER}" -le 75 ]]; then
# 50 < BATTERY < 75
ICON=""
COLOR="#11FF99"
else
# 75 < BATTERY
ICON=""
COLOR="#11FF66"
fi
else
ICON=""
COLOR="#11EE22"
fi

echo "${ICON} ${BATTERY_POWER}% ${TIME_LEFT}"
echo "${ICON} ${BATTERY_POWER}% ${TIME_LEFT}"
echo $COLOR

battery_level=$(acpi -b | grep -P -o '[0-9]+(?=%)')
if [ "$battery_level" -le 18 ]
then
    dunstify -t 1775 -h string:fgcolor:#000000 -h string:bgcolor:#FF0013 "LOW BATTERY! Please charge now!"
fi

if [ "$battery_level" -gt 99 ]
then
    dunstify -t 1775 -h string:fgcolor:#000000 -h string:bgcolor:#66FF13 "FULLY CHARGED! Please disconnect from power source."
fi
