#!/usr/bin/bash

FORMAT="${BLOCK_INSTANCE:-%a %e %b - %H:%M:%S}"
DATETIME=$(date "+${FORMAT}")

echo "${DATETIME}"
echo ""

case $BLOCK_BUTTON in
    1)termite -e "sh .config/i3-blocks/blocks/alarm";; # left click
esac
