#!/bin/bash

URGENT_VALUE=20

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(trizen -Su --aur --quiet | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$updates" -gt 0 ]; then
  echo "PMN " $updates_arch " | " "AUR " $updates_aur

else
    echo ""
fi

case $BLOCK_BUTTON in
    1)dunstify -t 1675 -h string:fgcolor:#FFFFFF -h string:bgcolor:#115F66 " Pacman Update";
      termite -e "sudo pacman -Syyu";;

    3)dunstify -t 1675 -h string:fgcolor:#FFFFFF -h string:bgcolor:#115F66 " Trizen Update";
      termite -e "trizen -Syyu";;

esac

 if [[ "${updates_arch}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
 fi



