#!/usr/bin/env bash

title=""
prompt=""
options=("Poweroff" "Reboot" "Hibernate" "Suspend")

echo "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do

    case "$CHOICE" in

    1 ) dunstify -t 1675 "$CHOICE" && systemctl poweroff;;
    2 ) dunstify -t 1675 "$CHOICE" && systemctl reboot;;
    3 ) dunstify -t 1675 "$CHOICE" && systemctl hibernate;;

    $(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
    *) echo "Invalid option. Try another one.";continue;;

    esac

done

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then {

while opt=$(dunstify -t 1675 -h string:fgcolor:#000F00 -h string:bgcolor:#66CC11 "POWER MENU" && zenity --title="$title" --text="$prompt" --list \
                    --column="Options" "${options[@]}
"); do

    case "$opt" in
    "${options[0]}" ) dunstify -t 1675 "$CHOICE" && systemctl poweroff;;
    "${options[1]}" ) dunstify -t 1675 "$CHOICE" && systemctl reboot;;
    "${options[2]}" ) dunstify -t 1675 "$CHOICE" && systemctl hibernate;;
    *) zenity --error --text="Invalid option. Try another one.";;
    esac

done
}
fi
